### ISSUE TITLE
agp2assembly.py produces a .assmbly file that shows scaffolds only in first chromosome 

### ISSUE THREAD

**Issue by gitcruz** [phasegenomics/juicebox_scripts#26]
Hi,

I am using JuiceBox (v1.11.08) to visualize the contact map of various assemblies (some  produced with SALSA2 and other with RagTag). I've managed to get the .hic files for these assemblies (using convert.sh for SALSA and running Juicer 1.6 in the other case). 

I then ran agp2assembly.py on the .agp files generated during the assemblies. 

The problem is that when I load both the .hic and .assembly file, Juicebox just shows the scaffolds for the first chromosome!!! for the rest of them it seems that this information is lost. Do you know what could be the reason and how to fix this?

Thanks in advance,
Fernando

**Comment by maximilianpress** [comment]
Hi Fernando, can you include your AGP/assembly files for us to inspect (or at least a sample for the one that works and the one that doesn't)? The script is expecting the file to show a specific format.

If you are getting any errors or other output from the script that would also be helpful.

Thanks, Max

**Comment by gitcruz** [comment]
Hi Max,

If you provide me your email address I could share one of the agp/assembly files with you. None of them worked, as I wrote, I am just being able to see the scaffolds that are part of the first chromosome (or super-scaffold) and not for the rest of the assembly.

Best,
Fernando

**Comment by maximilianpress** [comment]
You can send it to me at max@phasegenomics.com. If for some reason I don't respond you can also try support@phasegenomics.com. It would be helpful to have the AGP, assembly, and any outputs that you are getting from the script.

Thanks, Max

**Comment by gitcruz** [comment]
Cool, I will do that now.

The only difference between the SALSA and RagTag agp is that the first has
no header. Both give the same problem when loading the .assembly with the
.hic

Best,
Fernando

**Comment by maximilianpress** [comment]
I am not able to reproduce this issue. I am able to display all scaffolds, by clicking "ALL" in the Chromosomes drop-down selector of Juicebox using the provided .hic and .assembly files. However, there does seem to be an issue in which contigs are not represented in the .hic file. I will update according to further email correspondence with @gitcruz.

**Comment by maximilianpress** [comment]
In conversation with @gitcruz , it seems like the `.hic` file used in this case was not generated following our workflow, and is derived by mapping Hi-C reads to the pseudomolecules (results of Hi-C scaffolding) rather than the input contigs.

This will not work with our workflow (at least, I don't think it will work). It is necessary to use a BAM file of Hi-C reads mapped to **contigs** that are the input to the scaffolding process in generating the `.hic` file, as we lay out [here](https://github.com/phasegenomics/juicebox_scripts#getting-a-hic-file-from-a-bam-file-and-a-assembly-file).

I am going to submit a PR to the repo README to make this very clear; thanks @gitcruz for raising this to our attention!

**Comment by maximilianpress** [comment]
@gitcruz has confirmed to me that remaking the `.hic` file following our workflow succeeded in getting it to work in Juicebox.
